name: "pipeline2"
repository: "https://github.com/123sarahj123/artifacts-example.git"

steps:
  - command: true
    label: "Pipeline #2 : Job #1"
    concurrency: 1
    concurrency_group: 'sarahs-test-CG'
  - command: true
    label: "Pipeline #2 : Job #2"